- name: delete ec2 instances
  hosts: local
  connection: local
  tasks:
    - name: delete mongodb
      amazon.aws.ec2_instance:
        instance_ids:
          - i-0f683b4dd2715b1f9
        state: absent
        wait: true

    - name: delete redis
      amazon.aws.ec2_instance:
        instance_ids:
          - i-07aac966d90371135
        state: absent
        wait: true

    - name: delete mysql
      amazon.aws.ec2_instance:
        instance_ids:
          - i-0c287b3d44e00599a
        state: absent
        wait: true

    - name: delete rabbitmq
      amazon.aws.ec2_instance:
        instance_ids:
          - i-004fb3693aef68ab6
        state: absent
        wait: true


    - name: delete catalogue
      amazon.aws.ec2_instance:
        instance_ids:
          - i-0d021ccbf649f2b3c
        state: absent
        wait: true