- name: delete ec2 instances
  hosts: local
  connection: local

  tasks:

    - name: delete mongodb
      amazon.aws.ec2_instance:
        instance_ids:
          - i-05e0450294340e227
        state: absent
        wait: true

    - name: delete redis
      amazon.aws.ec2_instance:
        instance_ids:
          - i-029d8f8913e357b65
        state: absent
        wait: true