- name: delete ec2 instances
  hosts: local
  connection: local
  tasks:
    - name: delete mongodb
      amazon.aws.ec2_instance:
        instance_ids:
          - i-007c8b01d6f6acc04
        state: absent
        wait: true

    - name: delete redis
      amazon.aws.ec2_instance:
        instance_ids:
          - i-026afdb37228ffe31
        state: absent
        wait: true

    - name: delete mysql
      amazon.aws.ec2_instance:
        instance_ids:
          - i-08cc413584f8b1ed7
        state: absent
        wait: true